name: Run API Automation Tests (Cucumber + Extent)

on:
  workflow_dispatch:   # manual trigger

jobs:
  run-api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run tests (mvn clean test)
        run: mvn clean test

      # Upload Extent Report
      - name: Upload Extent Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: extent-report
          path: target/extent-reports/ExtentReport.html

      # Upload Cucumber HTML
      - name: Upload Cucumber HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-html-report
          path: target/cucumber-reports/cucumber.html

      # Upload Cucumber JSON
      - name: Upload Cucumber JSON (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-json
          path: target/cucumber-reports/cucumber.json

      # Prepare reports for GitHub Pages
      - name: Prepare reports for GitHub Pages
        if: always()
        run: |
          echo "Preparing reports for GitHub Pages..."
          rm -rf gh-pages-output || true
          mkdir -p gh-pages-output
          if [ -f target/cucumber-reports/cucumber.html ]; then
            cp target/cucumber-reports/cucumber.html gh-pages-output/cucumber.html
          fi
          if [ -f target/extent-reports/ExtentReport.html ]; then
            cp -r target/extent-reports/* gh-pages-output/
          fi

      # ✅ Deploy reports to GitHub Pages
      - name: Deploy reports to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gh-pages-output

