name: Run API Automation Tests (Cucumber + Extent)

on:
  workflow_dispatch:  # Manual trigger

jobs:
  run-api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run API Tests (mvn clean test)
        run: mvn clean test

      # Upload Extent Report
      - name: Upload Extent Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ExtentReport
          path: target/extent-reports/ExtentReport.html
